services:
  ollama:
    image: ollama/ollama
    container_name: yla_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  server:
    build: ./server
    container_name: yla_server
    ports:
      - "8000:8000"
    depends_on:
      - ollama

volumes:
  ollama: